### PR TITLE
Adding PIN confirmation before sending transactions, if enabled by us…

### PR DESCRIPTION
**Pull request by ottosch**
…er (default: off)

### CODE REVIEW

**Comment by Relaxo143** [comment]
This should definitely be merged in my opinion. (Considering that the code is ok and secure and that no critical bugs have been introduced). Security is #1 priority. I actually think that the pin before tx send should be always on and the pin before app start should be the optional one.

**Comment by SamouraiDev** [comment]
I haven't had time to look at this in detail. 2 quick remarks:
- null pointer tests have been removed for some reason. They were there for a reason.
- if I'm not mistaken (based on a quick glance) the setting is not saved to app payload.

Aside from that, I'll look more closely at it when I have the time. As far as pure functionality is concerned, I see zero need for it.

**Comment by ottosch** [comment]
Hey, TDev. Thank you for your review.

The progress variable is never null, as it's created at the beginning of validateThread():
`final ProgressDialog progress = new ProgressDialog(PinEntryActivity.this);`

I removed because the IDE was annoyingly saying all the time the null check was pointless, but I can put them back.


About the 2nd point, indeed I didn't consider that. I'll check that.

Thx.

**Comment by ottosch** [comment]
Fixed: option not being saved to wallet backup.

**Pull request closed without merging**
