### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by morovnicky**
Updated Slovak translation

### CODE REVIEW

**Comment by SamouraiDev** [comment]
Please resolve conflicts. There are duplicate strings and perhaps other issues. Thank you.

**Comment by SamouraiDev** [comment]
There are remaining duplicate strings.

**Comment by morovnicky** [comment]
I don´t know where can be a problem.

**Comment by SamouraiDev** [comment]
Lines 28-43 are duplicates of 45-56.

**Comment by morovnicky** [comment]
i was checking that and there are unique not duplicates . number of lines
are same as your master file (749)

**Comment by morovnicky** [comment]
pls check should be resolved

**Pull request merged**
